export const GET_STORIES_IDS = 'GET_STORIES_IDS';
export const DELETE_STORIES_IDS = 'DELETE_STORIES_IDS';
export const GET_STORIES_DETAILS = 'GET_STORIES_DETAILS';
export const DELETE_STORIES_DETAILS = 'DELETE_STORIES_DETAILS';
